"""Fix table name

Revision ID: 06642dac35a6
Revises: 88fa1d3a4940
Create Date: 2024-04-28 02:43:37.822147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06642dac35a6'
down_revision = '88fa1d3a4940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
