"""Fix table name

Revision ID: 118054da283f
Revises: 2248aa5011fa
Create Date: 2024-04-28 00:14:39.142007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118054da283f'
down_revision = '2248aa5011fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_period', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('payroll_period')

    # ### end Alembic commands ###
