"""empty message

Revision ID: 1890df3be21d
Revises: b28fc5f7b9ec
Create Date: 2023-05-29 01:48:58.274083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1890df3be21d'
down_revision = 'b28fc5f7b9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('employee_ibfk_1', type_='foreignkey')
        batch_op.drop_column('dep_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('employee_ibfk_1', 'department', ['dep_id'], ['id'])

    # ### end Alembic commands ###
