"""Initial

Revision ID: 2f5854ac3039
Revises: 6b3c5bf0e9ee
Create Date: 2023-08-14 08:32:56.406009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f5854ac3039'
down_revision = '6b3c5bf0e9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
