"""Fix table name

Revision ID: 357a766b379c
Revises: ceb33d85b957
Create Date: 2024-04-30 14:07:27.338377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '357a766b379c'
down_revision = 'ceb33d85b957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_salary', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('totalSalary', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.drop_column('salary')
        batch_op.drop_column('dep_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('totalSalary')
        batch_op.drop_column('basic_salary')

    # ### end Alembic commands ###
