"""empty message

Revision ID: 4a2ba570703a
Revises: b45078696198
Create Date: 2023-06-03 16:21:02.223411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a2ba570703a'
down_revision = 'b45078696198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('name')
        batch_op.drop_column('dep')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=400), nullable=False))
        batch_op.add_column(sa.Column('dep', mysql.VARCHAR(length=400), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=220), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
