"""empty message

Revision ID: 4ee550b8ddba
Revises: 789873943f74
Create Date: 2023-06-01 01:36:26.491602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ee550b8ddba'
down_revision = '789873943f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('dep_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
