"""Fix table name

Revision ID: 64321a2e9f88
Revises: f212aff658d2
Create Date: 2024-04-27 23:55:06.794792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64321a2e9f88'
down_revision = 'f212aff658d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=100), nullable=True))
        batch_op.drop_column('payroll_period')
        batch_op.drop_column('deductions')
        batch_op.drop_column('payroll_cycle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_cycle', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('deductions', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payroll_period', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
