"""Initial

Revision ID: 6b3c5bf0e9ee
Revises: 0fde95a9db7c
Create Date: 2023-08-13 23:49:57.560143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b3c5bf0e9ee'
down_revision = '0fde95a9db7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.drop_constraint('attandence_ibfk_1', type_='foreignkey')
        batch_op.drop_column('attan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attan_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('attandence_ibfk_1', 'attandence', ['attan_id'], ['id'])

    # ### end Alembic commands ###
