"""empty message

Revision ID: 701388946ede
Revises: 8486e092c960
Create Date: 2023-05-12 00:27:04.290184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701388946ede'
down_revision = '8486e092c960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attandence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('gender', sa.String(length=220), nullable=False),
    sa.Column('datetime', sa.Integer(), nullable=False),
    sa.Column('attan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('dep_id', sa.Integer(), nullable=True),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attan_id'], ['attandence.id'], ),
    sa.ForeignKeyConstraint(['dep_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['dep_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dep_id')

    op.drop_table('attandence')
    # ### end Alembic commands ###
