"""empty message

Revision ID: 72f1f1cd24e6
Revises: 4ee550b8ddba
Create Date: 2023-06-03 16:09:03.532140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72f1f1cd24e6'
down_revision = '4ee550b8ddba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('email', sa.String(length=400), nullable=False),
    sa.Column('dep', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.drop_index('email')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('name')
        batch_op.drop_column('email')
        batch_op.drop_column('dep')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep', mysql.VARCHAR(length=400), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=400), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=220), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('email', ['email'], unique=False)
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    op.drop_table('userr')
    # ### end Alembic commands ###
