"""empty message

Revision ID: 789873943f74
Revises: 72b1d9166587
Create Date: 2023-05-29 02:21:54.676048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789873943f74'
down_revision = '72b1d9166587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'department', ['dep_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dep_id')

    # ### end Alembic commands ###
