"""Initial

Revision ID: 7d7b21e402b6
Revises: e0e7a3acb6e5
Create Date: 2023-08-07 01:17:39.156383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7b21e402b6'
down_revision = 'e0e7a3acb6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['dep_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dep_id')

    # ### end Alembic commands ###
