"""Fix table name

Revision ID: 84af45927049
Revises: 06642dac35a6
Create Date: 2024-04-28 02:49:20.072185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84af45927049'
down_revision = '06642dac35a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
