"""empty message

Revision ID: b28fc5f7b9ec
Revises: 701388946ede
Create Date: 2023-05-22 16:49:32.250722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b28fc5f7b9ec'
down_revision = '701388946ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('dep_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('dep_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
