"""empty message

Revision ID: b45078696198
Revises: 72f1f1cd24e6
Create Date: 2023-06-03 16:17:12.964537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b45078696198'
down_revision = '72f1f1cd24e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userr', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('userr')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('dep')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=220), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=400), nullable=False))
        batch_op.add_column(sa.Column('dep', mysql.VARCHAR(length=400), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('userr',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=220), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('dep', mysql.VARCHAR(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('userr', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
