"""empty message

Revision ID: b4c27950175e
Revises: 4a2ba570703a
Create Date: 2023-06-03 16:24:05.328140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4c27950175e'
down_revision = '4a2ba570703a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('email')
        batch_op.drop_column('dep')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=220), nullable=False))
        batch_op.add_column(sa.Column('dep', mysql.VARCHAR(length=400), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=400), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
