"""Initial

Revision ID: b86c30228f50
Revises: 7d7b21e402b6
Create Date: 2023-08-11 07:10:04.274445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b86c30228f50'
down_revision = '7d7b21e402b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=220), nullable=False))

    # ### end Alembic commands ###
