"""Initial migration.

Revision ID: ba64fbdfd265
Revises: 513ef13925b4
Create Date: 2023-08-05 00:43:30.252070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba64fbdfd265'
down_revision = '513ef13925b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('datetime')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', mysql.VARCHAR(length=220), nullable=False))
        batch_op.add_column(sa.Column('datetime', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
