"""Fix table name

Revision ID: c699d24c2090
Revises: cb21f26e5dbd
Create Date: 2024-04-23 14:51:35.380719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c699d24c2090'
down_revision = 'cb21f26e5dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['dep_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dep_id')

    # ### end Alembic commands ###
