"""Fix table name

Revision ID: ceb33d85b957
Revises: 84af45927049
Create Date: 2024-04-28 02:50:43.575053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ceb33d85b957'
down_revision = '84af45927049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'department', ['dep_id'], ['id'])
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dep_id')

    # ### end Alembic commands ###
