"""Initial

Revision ID: e0e7a3acb6e5
Revises: ba64fbdfd265
Create Date: 2023-08-05 01:08:29.214038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e7a3acb6e5'
down_revision = 'ba64fbdfd265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attandence', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
