"""empty message

Revision ID: eb8bab590a69
Revises: 5f3db090081f
Create Date: 2023-05-04 20:00:05.235935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8bab590a69'
down_revision = '5f3db090081f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dep', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dep')

    # ### end Alembic commands ###
